# Generated by Django 5.1.7 on 2025-07-18 11:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epic', '0001_initial'),
        ('sprints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'Haute priorité'), ('medium', 'Priorité moyenne'), ('low', 'Faible priorité')], default='medium', max_length=10)),
                ('points', models.IntegerField(choices=[(1, '1 point'), (2, '2 points'), (3, '3 points'), (5, '5 points'), (8, '8 points'), (13, '13 points'), (21, '21 points')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(21)])),
                ('status', models.CharField(choices=[('ready', 'Prêt'), ('in_progress', 'En cours'), ('in_review', 'En révision'), ('testing', 'Test'), ('done', 'Terminé'), ('blocked', 'Bloqué')], default='ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstories', to='epic.epic')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userstories', to='sprints.sprint')),
            ],
            options={
                'verbose_name': 'User Story',
                'verbose_name_plural': 'User Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
