# Generated by Django 5.1.7 on 2025-07-18 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprints', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrospective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('what_worked', models.TextField()),
                ('what_didnt_work', models.TextField()),
                ('improvements', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospectives', to='sprints.sprint')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrospectives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
