# Generated by Django 5.1.7 on 2025-07-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation gratuite'), ('demo', 'Démonstration produit'), ('formation', 'Formation équipe'), ('audit', 'Audit processus'), ('integration', 'Intégration système')], max_length=50)),
            ],
        ),
    ]
