# Generated by Django 5.1.7 on 2025-07-18 11:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du sprint')),
                ('goal', models.TextField(verbose_name='Objectif du sprint')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('duration', models.PositiveIntegerField(choices=[(7, '1 semaine (7 jours)'), (14, '2 semaines (14 jours)'), (21, '3 semaines (21 jours)'), (28, '4 semaines (28 jours)')], default=14, verbose_name='Durée (jours)')),
                ('capacity', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Capacité (story points)')),
                ('planning_ceremony', models.BooleanField(default=True, verbose_name='Sprint Planning')),
                ('daily_ceremony', models.BooleanField(default=True, verbose_name='Daily Scrum')),
                ('review_ceremony', models.BooleanField(default=True, verbose_name='Sprint Review')),
                ('retrospective_ceremony', models.BooleanField(default=True, verbose_name='Rétrospective')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sprints', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['-start_date'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
