# Generated by Django 5.1.7 on 2025-07-18 11:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('userstory', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(default='general')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('deliverable_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('general', 'Feedback général'), ('ui-ux', 'Interface utilisateur'), ('functionality', 'Fonctionnalité'), ('performance', 'Performance'), ('bug', 'Problème technique'), ('suggestion', "Suggestion d'amélioration")], default='general', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='client.client', verbose_name='Client')),
                ('userstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='userstory.userstory')),
            ],
        ),
    ]
